
name: Flutter CICD

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
    - bfe

jobs:
  build_openapp_android:
    name: Build OpenApp Android
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta' or 'master'
    - run: flutter --version
    - run: flutter build apk
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk
  